### ISSUE TITLE
Firmware for SHT4x Smart Gadget

### ISSUE THREAD

**Issue by manumohannair** [Sensirion/smartgadget-sht4x-hardware#1]
Looks like Sht31 Smart Gadget code is different from Sht4x smart gadget. Is there a way I can get access Sht4x smart gadget firmware ? @MBjoern

**Comment by psachs** [comment]
The SHT4x smart gadget firmware does not have an open source release, therefore we unfortunately can't give you access to that code yet.
I will have to ask the firmware developers if they are willing to release this firmware publicly as well
