### ISSUE TITLE
3D model

### ISSUE THREAD

**Issue by SengerM** [Sensirion/smartgadget-sht4x-hardware#3]
Hello, thanks for making this available. Could you upload the 3D model of the board with all the components included? I have one of these and want to 3D print a custom case. I know about [this one](https://github.com/Sensirion/smartgadget-sht4x-housing), but need to make a different design. Any standard/open format should work, e.g. STEP or STL. 

Thanks!

**Comment by quentin-cy** [comment]
Hello @SengerM ,
Thank you for the suggestion. 
Your request has been heard and we will add a 3D model to this repository shortly.
Please let us know if we can help further.
Quentin

**Comment by quentin-cy** [comment]
It has been added to the repository.
Have a nice day :smiley:
